CREATE TABLE IF NOT EXISTS PATIENTS (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255),
    cpf VARCHAR(255) UNIQUE,
    address_id INTEGER UNIQUE,
    CONSTRAINT fk_patient_address FOREIGN KEY (address_id) REFERENCES ADDRESSES (id) ON DELETE CASCADE
);