version: '3.8'

services:
  patient-db:
    image: postgres:latest
    container_name: patient-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=patient-db
    ports:
      - "5433:5432"

  patient-app:
    build: .
    container_name: patient-app
    environment:
      - DB_URL=jdbc:postgresql://patient-db:5432/patient-db
      - DB_USER=user
      - DB_PASSWORD=password
    depends_on:
      - patient-db
    ports:
      - "8081:8080"